export const SUPPORTED_LANGUAGES = [
  { name: "Afar", code: "aa" },
  { name: "Abkhaz", code: "ab" },
  { name: "Afrikaans", code: "af" },
  { name: "Akan", code: "ak" },
  { name: "Aragonese", code: "an" },
  { name: "Avar", code: "av" },
  { name: "Aymara", code: "ay" },
  { name: "Azerbaijani", code: "az" },
  { name: "Belarusian", code: "be" },
  { name: "Bislama", code: "bi" },
  { name: "Bambara", code: "bm" },
  { name: "Breton", code: "br" },
  { name: "Catalan", code: "ca" },
  { name: "Chechen", code: "ce" },
  { name: "Chamorro", code: "ch" },
  { name: "Corsican", code: "co" },
  { name: "Cree", code: "cr" },
  { name: "Czech", code: "cs" },
  { name: "Welsh", code: "cy" },
  { name: "Danish", code: "da" },
  { name: "German", code: "de" },
  { name: "Ewe", code: "ee" },
  { name: "English", code: "en" },
  { name: "Esperanto", code: "eo" },
  { name: "Spanish", code: "es" },
  { name: "Estonian", code: "et" },
  { name: "Basque", code: "eu" },
  { name: "Fula", code: "ff" },
  { name: "Finnish", code: "fi" },
  { name: "Fijian", code: "fj" },
  { name: "Faroese", code: "fo" },
  { name: "French", code: "fr" },
  { name: "West Frisian", code: "fy" },
  { name: "Irish", code: "ga" },
  { name: "Scottish Gaelic", code: "gd" },
  { name: "Galician", code: "gl" },
  { name: "Manx", code: "gv" },
  { name: "Hausa", code: "ha" },
  { name: "Hiri Motu", code: "ho" },
  { name: "Haitian Creole", code: "ht" },
  { name: "Hungarian", code: "hu" },
  { name: "Herero", code: "hz" },
  { name: "Interlingua", code: "ia" },
  { name: "Indonesian", code: "id" },
  { name: "Interlingue", code: "ie" },
  { name: "Igbo", code: "ig" },
  { name: "Inupiaq", code: "ik" },
  { name: "Ido", code: "io" },
  { name: "Icelandic", code: "is" },
  { name: "Italian", code: "it" },
  { name: "Inuktitut", code: "iu" },
  { name: "Japanese", code: "ja" },
  { name: "Javanese", code: "jv" },
  { name: "Kongo", code: "kg" },
  { name: "Kikuyu", code: "ki" },
  { name: "Kwanyama", code: "kj" },
  { name: "Kazakh", code: "kk" },
  { name: "Greenlandic", code: "kl" },
  { name: "Kanuri", code: "kr" },
  { name: "Kashmiri", code: "ks" },
  { name: "Cornish", code: "kw" },
  { name: "Kyrgyz", code: "ky" },
  { name: "Latin", code: "la" },
  { name: "Luxembourgish", code: "lb" },
  { name: "Luganda", code: "lg" },
  { name: "Limburgish", code: "li" },
  { name: "Lingala", code: "ln" },
  { name: "Lithuanian", code: "lt" },
  { name: "Luba-Katanga", code: "lu" },
  { name: "Latvian", code: "lv" },
  { name: "Malagasy", code: "mg" },
  { name: "Marshallese", code: "mh" },
  { name: "Māori", code: "mi" },
  { name: "Mongolian", code: "mn" },
  { name: "Malay", code: "ms" },
  { name: "Maltese", code: "mt" },
  { name: "Nauruan", code: "na" },
  { name: "Norwegian Bokmål", code: "nb" },
  { name: "Northern Ndebele", code: "nd" },
  { name: "Ndonga", code: "ng" },
  { name: "Dutch", code: "nl" },
  { name: "Norwegian Nynorsk", code: "nn" },
  { name: "Norwegian", code: "no" },
  { name: "Southern Ndebele", code: "nr" },
  { name: "Navajo", code: "nv" },
  { name: "Chichewa", code: "ny" },
  { name: "Occitan", code: "oc" },
  { name: "Ojibwe", code: "oj" },
  { name: "Oromo", code: "om" },
  { name: "Ossetian", code: "os" },
  { name: "Pali", code: "pi" },
  { name: "Polish", code: "pl" },
  { name: "Portuguese", code: "pt" },
  { name: "Quechua", code: "qu" },
  { name: "Romansh", code: "rm" },
  { name: "Romanian", code: "ro" },
  { name: "Rwanda-Rundi", code: "rw" },
  { name: "Sardinian", code: "sc" },
  { name: "Northern Sami", code: "se" },
  { name: "Sango", code: "sg" },
  { name: "Serbo-Croatian", code: "sh" },
  { name: "Slovak", code: "sk" },
  { name: "Slovene", code: "sl" },
  { name: "Samoan", code: "sm" },
  { name: "Shona", code: "sn" },
  { name: "Somali", code: "so" },
  { name: "Albanian", code: "sq" },
  { name: "Swazi", code: "ss" },
  { name: "Sotho", code: "st" },
  { name: "Sundanese", code: "su" },
  { name: "Swedish", code: "sv" },
  { name: "Swahili", code: "sw" },
  { name: "Tajik", code: "tg" },
  { name: "Turkmen", code: "tk" },
  { name: "Tagalog", code: "tl" },
  { name: "Tswana", code: "tn" },
  { name: "Tongan", code: "to" },
  { name: "Turkish", code: "tr" },
  { name: "Tsonga", code: "ts" },
  { name: "Tatar", code: "tt" },
  { name: "Tahitian", code: "ty" },
  { name: "Uyghur", code: "ug" },
  { name: "Uzbek", code: "uz" },
  { name: "Venda", code: "ve" },
  { name: "Vietnamese", code: "vi" },
  { name: "Volapük", code: "vo" },
  { name: "Walloon", code: "wa" },
  { name: "Wolof", code: "wo" },
  { name: "Xhosa", code: "xh" },
  { name: "Yiddish", code: "yi" },
  { name: "Yoruba", code: "yo" },
  { name: "Zhuang", code: "za" },
  { name: "Chinese", code: "zh" },
  { name: "Zulu", code: "zu" },
];

export const BASE_LANGUAGE = "English";
